---
title: "STAT 184 Activity 7"
output: html_notebook
---

## Front Matter
```{r}
library(tidyverse)
data("iris")
data("mtcars")
```

## Problem 1
```{r}
ggplot(data = iris, mapping = aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point() +
  labs(x = "Sepal Length (in cm)",
       y = "Sepal Width (in cm)")
```


```{r}
ggplot(data = iris, mapping = aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point(color = "orange") +
  labs(x = "Sepal Length (in cm)",
       y = "Sepal Width (in cm)")
```


```{r}
ggplot(data = iris, mapping = aes(x = Sepal.Length, y = Sepal.Width,
                                  color = Species)) +
  geom_point() +
  labs(x = "Sepal Length (in cm)",
       y = "Sepal Width (in cm)")
```

```{r}
ggplot(data = iris, mapping = aes(x = Sepal.Length, y = Sepal.Width,
                                  color = Species)) +
  geom_point() +
  labs(x = "Sepal Length (in cm)",
       y = "Sepal Width (in cm)") +
  scale_color_manual(values=c("orange", "green", "navy"))
```

```{r}
ggplot(data = iris, mapping = aes(x = Sepal.Length, y = Sepal.Width,
                                  color = Species)) +
  geom_point() +
  labs(x = "Sepal Length (in cm)",
       y = "Sepal Width (in cm)") +
  scale_color_manual(values=c("orange", "green", "navy")) +
  theme(legend.position="bottom")
```

```{r}
ggplot(data = iris, mapping = aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point() +
  geom_smooth(method = "lm", se=FALSE) +
  facet_grid(. ~ Species) +
  labs(x = "Sepal Length (in cm)",
       y = "Sepal Width (in cm)") +
  scale_color_manual(values=c("orange", "green", "navy")) +
  theme(legend.position="top") + 
  theme_bw()
```

```{r}
ggplot(data = iris, mapping = aes(x = Species, y = Sepal.Width)) +
  geom_boxplot() +
  labs(x = "Species",
       y = "Sepal Width (in cm)") +
  #scale_color_manual(values=c("orange", "green", "navy")) +
  #theme(legend.position="top")
  theme_bw()
```

```{r}
iris2 <- iris %>%
         #recode(Species, setosa = "Setosa", virginica = "Virginica",versicolor = "Versicolor") %>%
         mutate(Species = factor(Species, levels = c("setosa", "virginica", "versicolor")))

ggplot(data = iris2, mapping = aes(x = Species, y = Sepal.Width)) +
  geom_boxplot() +
  labs(x = "Species",
       y = "Sepal Width (in cm)") +
  #scale_color_manual(values=c("orange", "green", "navy")) +
  #theme(legend.position="top")
  theme_bw()

```

```{r}
ggplot(data = iris, mapping = aes(x = Sepal.Length, y = Sepal.Width,
                                  color = Species)) +
  geom_point() +
  labs(x = "Sepal Length (in cm)",
       y = "Sepal Width (in cm)") +
  scale_color_manual(values=c("orange", "green", "navy")) +
  theme(legend.position="bottom") +
  scale_x_continuous(breaks = seq(4,8,0.5), limits = c(4,8
                                                       ))
```

